### ISSUE TITLE
Conflics with realm version

### ISSUE THREAD

**Issue by mgohin** [jonasrottmann/realm-browser#10]
Hi,

just followed the readme :

    debugCompile('com.github.jonasrottmann.realm-browser:realm-browser:v0.0.9') {
        exclude group: 'com.android.support'
    }
    testCompile('com.github.jonasrottmann.realm-browser:realm-browser-no-op:v0.0.9') {
        exclude group: 'com.android.support'
    }
    releaseCompile('com.github.jonasrottmann.realm-browser:realm-browser-no-op:v0.0.9') {
        exclude group: 'com.android.support'
    }

but got this :

    Error:Conflict with dependency 'io.realm:realm-android-library' in project ':myproject'. Resolved versions for app (3.1.2) and test app (3.0.0) differ. See http://g.co/androidstudio/app-test-app-conflict for details.
    Error:Conflict with dependency 'io.realm:realm-annotations' in project ':myproject'. Resolved versions for app (3.1.2) and test app (3.0.0) differ. See http://g.co/androidstudio/app-test-app-conflict for details.

Could you do something not to get errors when realm version is different ?

edit : Between 3.0.0 and 3.1.2 they have done a migration, maybe that's why it's conflicting ?
I made it work with realm 3.0.0, thank you sooooo much for this ! So usefull for people without an OSX 👍

**Comment by mgohin** [comment]
Up because I think it's pretty simple to update for you and we really need to keep realm latest version

**Comment by jonasrottmann** [comment]
Sorry, was on vacation the last weeks 🤷‍♂️ Just released a new version `0.0.10` (note: I removed the `v` from new version names), which uses realm `3.1.2`. Please test and report back 🤓

**Comment by mgohin** [comment]
Vacations ... it should be forbidden :p
Thanks, it works perfectly !

**Comment by mgohin** [comment]
Hi,

same prob with 3.1.4 ;)

**Comment by jonasrottmann** [comment]
Browser version `0.0.12` should work again with Realm `3.1.4`

**Comment by mgohin** [comment]
Nice, thx for your reactivity.
See you for the next Realm update ;)

**Comment by mgohin** [comment]
Hello,

please update for Realm 3.3.1 ;)

**Comment by mgohin** [comment]
up ;)

**Comment by jonasrottmann** [comment]
Updated to Realm 3.3.1 with [Version 0.0.14](https://github.com/jonasrottmann/realm-browser/releases/tag/0.0.14).

**Comment by mgohin** [comment]
Hello it's me again, Realm 3.4.0 :)
