### ISSUE TITLE
Cannot use library in different flavors of an application

### ISSUE THREAD

**Issue by jonasrottmann** [jonasrottmann/realm-browser#20]
The FileProvider authority does not change across different variants of an app (or different apps), which results in an installation error "Conflicting Providers".

Don't really know how to solve this issue... [corresponding StackOverflow post](http://stackoverflow.com/questions/44073845/fileprovider-authority-in-android-library-project)

**Comment by paulVulog** [comment]
Any solution on it @jonasrottmann ? Let me know about your progress. I can perhaps help you since I am stuck with this issue on my apps. Looks like getting the provider android:authorities from the parent application seems the right solution.

**Comment by jonasrottmann** [comment]
This should be fixed with [version 0.0.14](https://github.com/jonasrottmann/realm-browser/releases/tag/0.0.14)

**Comment by paulVulog** [comment]
Amazing @jonasrottmann . I confirm it works fine ! 👍
