### ISSUE TITLE
Compatibility broke since Realm 0.91.0

### ISSUE THREAD

**Issue by degill** [jonasrottmann/realm-browser#3]
Since Realm v0.91.0 all deprecated methods were remove. This is particular bad for the method `DynamicRealm#allObjects` used by the realm-browser. As such, the content of realm-tables can not be viewed, the app rather crashes.

This is concerning.

**Comment by jonasrottmann** [comment]
You can use the snapshot of the develop branch
`compile "com.github.jonasrottmann.realm-browser:realm-browser:develop-SNAPSHOT"`.
This problem should be resolved there.
