### ISSUE TITLE
Allow sharing of the/all realm files

### ISSUE THREAD

**Issue by degill** [jonasrottmann/realm-browser#9]
It would be nice to have a share button to export the/all actual realm files to be able to view them within the realm-browser desktop client.

**Comment by jonasrottmann** [comment]
That's definitely something I want to implement. I thought about being able to share the .realm database file from a menu-item on the ModelsActivity as well as the BrowserActivity. On the ObjectActivity we could give the option to share a String representation of the object which is currently displayed.

**Comment by jonasrottmann** [comment]
e20bd75ec0269d8545a9ed6874789baf4d9ccf23 added the option to share the currently opened file from the ModelsActivity 😎
